[package]
name = "concierge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
io-uring = { version = "0.5.2", features = ["unstable"] }
slab = "0.4.6"
rand = "0.8.5"

net = { path = "../net" }
binary = { path = "../binary" }
protocol = { path = "../protocol" }
